# Generated by Django 2.2 on 2019-06-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistId',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artistType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.SlugField(),
        ),
    ]
