# Generated by Django 2.2 on 2019-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190630_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistId',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
