# Generated by Django 2.2 on 2019-06-30 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0004_auto_20190630_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumId',
            field=models.PositiveIntegerField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='albumType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='song',
            name='songId',
            field=models.PositiveIntegerField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='songType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistId',
            field=models.PositiveIntegerField(default=uuid.uuid4, unique=True),
        ),
    ]
