# Generated by Django 2.2 on 2019-06-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190630_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('songName',)},
        ),
        migrations.AddField(
            model_name='song',
            name='Album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Album'),
            preserve_default=False,
        ),
    ]
