# Generated by Django 2.2.3 on 2019-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190630_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='songName',
            field=models.CharField(max_length=20),
        ),
    ]
